title: SQL Tutorial
repository: gvwilson/sql-tutorial
author:
  name: Greg Wilson

chapters:
- title: "Our Database"
  path: "00_db"
- title: "Selecting Columns"
  path: "01_select"
- title: "Sorting Output"
  path: "02_sort"
- title: "Calculating Values"
  path: "03_calculate"
- title: "Dates and Times"
  path: "04_calculate"
- title: "Filtering"
  path: "04_filter"
- title: "Missing Data"
  path: "05_null"

defaults:
- scope:
    path: ""
  values:
    layout: "default"

markdown: kramdown
highlighter: rouge

include:
  - _md

exclude:
  - CODE_OF_CONDUCT.md
  - LICENSE.md
  - README.md
  - '.#*'
  - '*~'

permalink: pretty
